apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: argo-cp
  region: us-west-2

managedNodeGroups:
  - name: argo-cp
    instanceTypes: [ "t2.medium", "t3.medium" ]
    desiredCapacity: 1
    volumeSize: 20