apiVersion: opm.paas.org/v1alpha1
kind: OpmS3Bucket
metadata:
  name: opms3bucket
  namespace: crossplane-system-dev

spec:
  parameters:
    LocationConstraint: "us-west-2"
    acl: "private"
    VersioningConfiguration: "Enabled"
    Bucket: "aws-crossplane-s3-composition-bucket"
    Namespace: "crossplane-system-dev"
    Forcedestroy: "false"
  compositionSelector:
    matchLabels:
      provider: terraform-provider
      team: opm